{{- if ne .Values.targetNamespace "openshift-operators" -}}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.targetNamespace }}-operator-group
  namespace: {{ .Values.targetNamespace }}
spec:
  targetNamespaces:
    - {{ .Values.targetNamespace }}
{{- end }}